### ISSUE TITLE
add sortBy option

### ISSUE THREAD

**Issue by radiovisual** [DerHowie/word-cataloguer#3]
it would be cool to have the option to get a returned value with the most popular words first:

In Descending order:
```js
wordCataloguer('Santa says Yo Yo Yo!', {sortBy:'DESC'});
/*
    'Yo': 3 
    'says': 1 
    'Santa': 1
*/
```

and in Ascending order:
```js
wordCataloguer('Santa says Yo Yo Yo!', {sortBy:'ASCN'});
/*
    'says': 1
    'Santa': 1
    'Yo': 3
*/
```

**Comment by DerHowie** [comment]
I have added an "order" option to the module. By default the module now returns objects in descending order and ascending order can be accessed with the following syntax: 

```js
wordCataloguer('Santa says Yo Yo Yo!', {order: 'asc'});
// => [{word: 'Santa', count: 1}, {word: 'says', count: 1}, {word: 'Yo', count: 3}]
```
