### ISSUE TITLE
cs => caseSensitive || lowerCase

### ISSUE THREAD

**Issue by radiovisual** [DerHowie/word-cataloguer#5]
your API options should be readable and descriptive.

If I saw this line of code, I would have to read the source to know what `cs` means:
```js
cataloger('Words here!', {cs: true});
```

But if I saw this, I would immediately have an Idea of what is going on:

```js
cataloger('Words here!', {caseSensitive: true});
```

If you wanted to keep the option names a little shorter (save the user a little typing), you can try to find descriptive names that are shorter in length:

```js
cataloger('Words here!', {ignoreCase: false});
cataloger('Words here!', {useCase: false});
cataloger('Words here!', {lowerCase: true});
```

I think my favorite of these options as far as readability goes, is `lowerCase`:
```js
cataloger('Words here!', {lowerCase: true});
```

👍

**Comment by DerHowie** [comment]
You can now access the case-sensitive option with the following syntax:

```js
wordCataloguer('string', {caseSensitive: true});
```

**Comment by radiovisual** [comment]
@DerHowie , dont forget to update [this header in the readme](https://github.com/DerHowie/word-cataloguer/blob/master/readme.md#case-sensitive-cs-true).
